sudo: required

env:
  global:
    - HUGO_VER=0.55.6
    - ENCRYPTION_LABEL="ab5fa77f9e84"
    - COMMIT_AUTHOR_EMAIL="clint@clintarmstrong.net"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-pygments
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_${HUGO_VER}_Linux-64bit.deb
  - sudo dpkg -i ./hugo_${HUGO_VER}_Linux-64bit.deb

install: true

script: hugo -d ./public

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: false
  local_dir: ./public
  target_branch: master
  on:
    branch: src

branches:
  only:
    - src
