sudo: required

env:
  global:
    - HUGO_VER=0.55.6
    - ENCRYPTION_LABEL="ab5fa77f9e84"
    - COMMIT_AUTHOR_EMAIL="clint@clintarmstrong.net"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-pygments
  - wget https://github.com/gohugoio/hugo/releases/download/v${HUGO_VER}/hugo_${HUGO_VER}_Linux-64bit.deb
  - sudo dpkg -i ./hugo_${HUGO_VER}_Linux-64bit.deb

install: true

script: bash ./deploy.sh

branches:
  only:
    - src
