sudo: required

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y python-pygments
  - wget https://github.com/spf13/hugo/releases/download/v0.19/hugo_0.19-64bit.deb
  - sudo dpkg -i ./hugo_0.19-64bit.deb

install: true

script: bash ./deploy.sh

env:
  global:
    - ENCRYPTION_LABEL="ab5fa77f9e84"
    - COMMIT_AUTHOR_EMAIL="clint@clintarmstrong.net"

branches:
  only:
    - src
