#Title: "Devops Discoveries" I hate this title, who needs a title anyway
languageCode: "en-us"
baseurl: "https://clinta.github.io"
theme: "clinta"
PygmentsCodeFences: true
pygmentsstyle: "friendly"
Author:
  name: "Clint Armstrong"
  email: "clint@clintarmstrong.net"
permalinks:
  post: /:slug/
googleAnalytics: "UA-58778705-1"

params:
  headerlinks:
    - Posts: /
    - Twitter: https://twitter.com/clinta

Indexes:
  tag: "tags"
